# Override for staging environment
# Used together with docker-compose.yml
# Run: docker compose -f docker-compose.yml -f docker-compose.staging.yml up -d

services:
  db:
    env_file:
      - .env.staging

  prestart:
    env_file:
      - .env.staging

  backend:
    env_file:
      - .env.staging

  frontend:
    env_file:
      - .env.staging

  # Mailcatcher for local email testing
  mailcatcher:
    image: schickling/mailcatcher
    restart: always
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      - default
